encyclopedia/urls.py
from django.urls import path, re_path
from . import views, util
import re

app_name = "wiki"
urlpatterns = [
	path("", views.goIndex, name="goIndex"), # user types no address
    path("wiki/", views.index, name="index"),
    path("wiki/createEntry/", views.createEntry, name="createEntry"),
    path("wiki/editEntry/<id>/", views.editEntry, name="editEntry"),
    path("wiki/randomArticle/", views.randomArticle, name="randomArticle"),
]

newurl = ""
for article in util.list_entries():
	newurl = app_name+"/"+article
	urlpatterns.append(path(newurl, views.article, name=article))

urlpatterns.append(re_path(r'^(?P<path>.*)/$', views.notFound))

# articles must be inserted at the beginning as the not-found page in the line just upper must come last as a fall-through option to catch urls that don't exist.
def insertArticleAtBeginning(articleName): 
		urlpatterns.insert(0, path("wiki/"+articleName, views.article, name=articleName))

wiki/urls.py
from django.contrib import admin
from django.urls import include, path

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include("encyclopedia.urls"))
]

encyclopedia/models.py
from django.db import models

# Create your models here.

encyclopedia/views.py
from django.shortcuts import render, redirect
from django.urls import path
from django.urls import resolve
from django import forms
from . import util, urls
import re
from django.http import HttpResponse
import random
import markdown

def goIndex(request):
	return redirect("wiki/")

def index(request):
	search = request.GET.get('search')
	if (search):
		return getit(request, search)
	else:
		return render(request, "encyclopedia/index.html", {"entries": util.list_entries()})
		
def article(request):
	search = request.GET.get('search')
	articleTitle = resolve(request.path_info).url_name
	if (search):
		return getit(request, search)
	else:
		return getit(request, articleTitle)
		
def getit(request, search):
	if util.get_entry(search) is not None:
		return render(request, "encyclopedia/article.html",{"content": markdown.markdown(util.get_entry(search)),"title": search })
		
	listOfEntries = util.list_entries()
	listOfFinds = []
	count = 0
	
	while count < len(listOfEntries): # for-loop wouldn't work, type error (assumes count to be str)
		x = re.search(search.lower(), listOfEntries[count].lower())
		if (x is not None):
			listOfFinds.append(listOfEntries[count])
		count += 1
		
	if len(listOfFinds) > 0:
		return render(request, "encyclopedia/searchResult.html", {"finds": listOfFinds,"title":"Search Results"})
	else:
		return render(request, "encyclopedia/notFound.html",{"content": "No article could be found for your search.","title": "No results found!"})

def notFound(request, path):
	return render(request, "encyclopedia/notFound.html",{"content": "There's no article for the URL you've tried.","title": "Article not found."})
	
def createEntry(request):
	if request.method == "POST":
		form = NewArticle(request.POST)
		if form.is_valid():
			article = form.cleaned_data["article"]
			title = form.cleaned_data["title"]
			
			#check for existing article with same title
			listOfEntries = util.list_entries()
			count = 0
			while count < len(listOfEntries):
				if (title.lower() == listOfEntries[count].lower()):
					return render(request, "encyclopedia/notFound.html",{"content": f"An article with the title {title} already exists.","title": "Entry already exists!" })
				count += 1
			
			util.save_entry(title, article)
			urls.insertArticleAtBeginning(title)
			return getit(request, title)
		
		else:
			return render(request, "encyclopedia/createEntry.html", {
                "form": form})
	
	return render(request, "encyclopedia/createEntry.html", {
        "form": NewArticle()})

def editEntry(request, id):
	title = id
	article = util.get_entry(title)
	#print(article)
	#print(article.encode())
	if request.method == "POST":
		form = NewArticle(request.POST)
		if form.is_valid():
			article = form.cleaned_data["article"]
			title = form.cleaned_data["title"]
			util.save_entry(title, article.encode()) #if it wasn't for .encode() linebreaks would double every time in the textarea window (innerText, not innerHTML), both the \r and \n would double at every save. See it by uncommenting the two prints upper in this function and removing encode() from the parameter of util.save_entry
			# https://stackoverflow.com/questions/69216585/newline-character-n-duplicates-when-writing-a-file-with-python#:~:text=I%20had%20the%20same%20problem%2C%20saving%20markdown%20files,now%20it%20can%20be%20saved%20into%20a%20file
		return getit(request, id)
	return render(request, "encyclopedia/createEntry.html", {
        "form": NewArticle(initial={'title':title,'article':article})})
	
class NewArticle(forms.Form):
	title = forms.CharField(label = '')
	article = forms.CharField(widget = forms.Textarea, label ='')

def randomArticle(request):
	listOfEntries = util.list_entries()
	article = listOfEntries[(random.randint(0, len(listOfEntries)-1))]
	return redirect(f"wiki:{article}")

encyclopedia/templates/encyclopedia/article.html
{% extends "encyclopedia/layout.html" %}
{% block title %}
{{ title.id | safe}}
{% endblock %}
<div class = 'main'>
{% block body %}
{{ content | safe}}
<br><br><a href="{% url 'wiki:editEntry' id=title %}">Edit this Article</a>
{% endblock %}
</div>

encyclopedia/templates/encyclopedia/createEntry.html
{% extends "encyclopedia/layout.html" %}
{% load static %}

{% block title %}
{{ title }}
{% endblock %}


{% block body %}
    <h1>Create An Article</h1>
    <form action="" method="post">
    	{% csrf_token %}
    	{{ form }}
        <input type="submit">
    </form>
{% endblock %}

encyclopedia/templates/encyclopedia/index.html
{% extends "encyclopedia/layout.html" %}

{% block title %}
    Encyclopedia
{% endblock %}

{% block body %}
    <h1>All Pages</h1>

    <ul>
        {% for entry in entries %}
            <li><a href="{{entry}}">{{entry}}</a></li>
        {% endfor %}
    </ul>

{% endblock %}

encyclopedia/templates/encyclopedia/layout.html
{% load static %}

<!DOCTYPE html>

<html lang="en">
    <head>
        <title>{% block title %}{% endblock %}</title>
        <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/css/bootstrap.min.css" integrity="sha384-Vkoo8x4CGsO3+Hhxv8T/Q5PaXtkKtu6ug5TOeNV6gBiFeWPGFN9MuhOf23Q9Ifjh" crossorigin="anonymous">
        <link href="{% static 'encyclopedia/styles.css' %}" rel="stylesheet">
    </head>
    <body>
        <div class="row">
            <div class="sidebar">
                <h2>Wiki</h2>
                <form ction="{% url 'wiki:index' %}">
                    <input class="search" type="search" name="search" placeholder="Search Encyclopedia" id='input'>
                </form>
                <div>
                    <a href="{% url 'wiki:index' %}">Home</a>
                </div>
                <div>
                    <a href="{% url 'wiki:createEntry' %}" id="createEntry">Create New Page</a>
                </div>
                <div>
                    <a href="{% url 'wiki:randomArticle' %}" id="randomEntry">Random Page</a>
                </div>
                {% block nav %}
                {% endblock %}
            </div>
            <div class="main">
                {% block body %}
                {% endblock %}
            </div>
        </div>
    </body>
    <script>
    </script>
</html>

encyclopedia/templates/encyclopedia/notFound.html
{% extends "encyclopedia/layout.html" %}
{% block title %}
{{ title | safe}}
{% endblock %}
{% block body %}
{{ content | safe}}
{% endblock %}

encyclopedia/templates/encyclopedia/searchResult.html
{% extends "encyclopedia/layout.html" %}
{% block title %}
{{ title }}
{% endblock %}

{% block body %}
	<h1>Matches Found:</h1>
	
    <ul>
        {% for find in finds %}
            <li><a href="{{find}}">{{find}}</a></li>
        {% endfor %}
    </ul>
{% endblock %}